### ISSUE TITLE
Multi-variative ts forecasting

### ISSUE THREAD

**Issue by valer1435** [valer1435/RepoPilot#28]
How to use Fedot for multivariate ts forecasting?

**Comment by RepoPilotAssistant** [comment]
👋 Welcome to the Issue Discussion!

Hello there! I'm here to assist you with any questions. 

Please feel free to share your thoughts, and I'll do my best to provide you with the information or support you need. Let's work together to resolve any issues and make things better!

Looking forward to your input! 🌟. To ask me just tag @RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by valer1435** [comment]
help

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
Hope this helps! If you need any further assistance or have more questions, feel free to ask.

**Please follow links below:**
1. [Plot of the forecast:](https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html)
2. [Plot of the forecast:](https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html)
3. [Time Series Forecasting](https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html)
4. [Time Series Forecasting — FEDOT 0.7.4 documentation](https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html)
5. [Plot of the forecast:](https://fedot.readthedocs.io/en/latest/basics/ts_forecasting.html)
