### ISSUE TITLE
vllm tools

### ISSUE THREAD

**Issue by valer1435** [valer1435/RepoPilot#39]
Please give link to the tools implementation in code

**Comment by RepoPilotAssistant** [comment]
👋 Welcome to the Issue Discussion!

Hello there! I'm here to assist you with any questions. 

Please feel free to share your thoughts, and I'll do my best to provide you with the information or support you need. Let's work together to resolve any issues and make things better!

Looking forward to your input! 🌟. To ask me just tag @RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
Sorry, I'm unable answer your question with information I have.

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
Sorry, I'm unable answer your question with information I have.

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
The implementation of tools in the code involves several key components:

1. **Tool Usage Validation**:
   - The code ensures that if `tool_choice` is specified, `tools` must be provided.
   - It validates that `tool_choice` is either a named tool or set to "auto".
   - If `tool_choice` is specified as an object, it checks that it matches a valid tool from the provided `tools`.

2. **Tool Choice Handling**:
   - If `tool_choice` is not specified but `tools` are provided, it defaults `tool_choice` to "auto".
   - It ensures that `tool_choice` is correctly formatted and matches a valid tool if specified as an object.

3. **Tool Parsing**:
   - The `ToolParser` class is an abstract class that initializes properties and methods for derived classes to handle tool parsing.
   - It includes properties like `prev_tool_call_arr`, `current_tool_id`, `current_tool_name_sent`, and `streamed_args_for_tool` to manage the state of tool parsing.
   - The `vocab` property is cached to store the vocabulary used by the tokenizer.

These components work together to ensure that tools are correctly specified, validated, and parsed within the system.

**Please follow links below:**
1. [78}]](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_with_tools.html)
2. [78}]](https://docs.vllm.ai/en/stable/getting_started/examples/openai_chat_completion_client_with_tools.html)
3. [How to write a tool parser plugin#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
4. [Jamba Models (jamba)#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
5. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)

**Comment by valer1435** [comment]
Which format for tool call should I use? @RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
You should use the JSON-based tool call format.

**Please follow links below:**
1. [78}]](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_with_tools.html)
2. [78}]](https://docs.vllm.ai/en/stable/getting_started/examples/openai_chat_completion_client_with_tools.html)
3. [How to write a tool parser plugin#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
4. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
5. [Jamba Models (jamba)#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)

**Comment by valer1435** [comment]
Which format for tool call should I use? @RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
You should use the JSON-based tool call format.

**Please follow links below:**
1. [78}]](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_with_tools.html)
2. [78}]](https://docs.vllm.ai/en/stable/getting_started/examples/openai_chat_completion_client_with_tools.html)
3. [How to write a tool parser plugin#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
4. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
5. [Jamba Models (jamba)#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)

**Comment by valer1435** [comment]
Which format for tool call should I use? @RepoPilotAssistant

**Comment by valer1435** [comment]
Which format for tool call should I use? @RepoPilotAssistant

**Comment by valer1435** [comment]
Which format for tool call should I use? @RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
You should use the JSON-based tool call format.

**Please follow links below:**
1. [78}]](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_with_tools.html)
2. [78}]](https://docs.vllm.ai/en/stable/getting_started/examples/openai_chat_completion_client_with_tools.html)
3. [How to write a tool parser plugin#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
4. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
5. [Jamba Models (jamba)#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)

**Comment by valer1435** [comment]
Can you explain detailed? @RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
The JSON-based tool call format is used for tool calling in the chat completion API. This format is supported in Llama models, specifically for models like `meta-llama/Meta-Llama-3.1-8B-Instruct`, `meta-llama/Meta-Llama-3.1-70B-Instruct`, and `meta-llama/Meta-Llama-3.1-405B-Instruct`. This format allows you to specify tools and their parameters in a structured JSON format, which is then used by the model to perform the desired tool-based actions.

**Please follow links below:**
1. [78}]](https://docs.vllm.ai/en/latest/getting_started/examples/openai_chat_completion_client_with_tools.html)
2. [78}]](https://docs.vllm.ai/en/stable/getting_started/examples/openai_chat_completion_client_with_tools.html)
3. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html)
4. [How to write a tool parser plugin#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
5. [Tool calling in the chat completion API#](https://docs.vllm.ai/en/stable/serving/openai_compatible_server.html)
