### ISSUE TITLE
How fedot works?

### ISSUE THREAD

**Issue by valer1435** [valer1435/RepoPilot#7]
I wonder to understand how fedot works.

**Comment by valer1435** [comment]
@RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
@valer1435 I don't know the answer to your question based on the provided information. Please refer to the documentation or source files for more details. If you have a specific example or step-by-step guide you need, please provide more context so I can assist you better.

**Comment by valer1435** [comment]
I want to know which concepts lies under Fedot

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by valer1435** [comment]
@RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
@valer1435 Based on the provided information, Fedot encompasses several key concepts including its AutoML API, data handling, pipeline composition, and model tuning. Here’s a brief overview:

1. **AutoML API**: The main class `Fedot` allows you to define the type of modeling problem (classification, regression, or time series forecasting), set parameters like timeout, task-specific parameters, and more. It provides methods for fitting models, tuning hyperparameters, and making predictions.

2. **Data Handling**: Fedot uses its own data object notation (`InputData`) which can be created from various formats like CSV files, pandas DataFrames, or numpy arrays. It supports different task types such as classification, regression, and time series forecasting.

3. **Pipeline Composition**: The `fit` method composes and fits a new pipeline or fits a predefined one. Pipelines can be visualized and saved for later use.

4. **Model Tuning**: The `tune` method allows for hyperparameters tuning of the current pipeline, with options to set metrics, iterations, timeout, and more.

For more detailed examples and step-by-step guides, you can refer to the specific sections in the documentation such as the "Classification example" and "Working with data" sections. If you need a specific example or further assistance, please provide more context.

**Comment by valer1435** [comment]
How I can solve classification problem with Fedot? @RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
@valer1435 To solve a classification problem with Fedot, you can follow these steps:

1. **Import the necessary module**:
   ```python
   from fedot.api.main import Fedot
   ```

2. **Load your training and test data**:
   ```python
   import pandas as pd
   train = pd.read_csv('train.csv')
   test = pd.read_csv('test.csv')
   ```

3. **Initialize the Fedot object for classification**:
   ```python
   model = Fedot(problem='classification', metric='roc_auc')
   ```

4. **Fit the model to your training data**:
   ```python
   best_pipeline = model.fit(features=train, target='target')
   ```

5. **Make predictions on the test data**:
   ```python
   prediction = model.predict(features=test)
   ```

6. **Evaluate the model's performance**:
   ```python
   metrics = model.get_metrics()
   print(metrics)
   ```

Here's a complete example:

```python
from fedot.api.main import Fedot
import pandas as pd

# Load data
train = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

# Initialize Fedot for classification
model = Fedot(problem='classification', metric='roc_auc')

# Fit the model
best_pipeline = model.fit(features=train, target='target')

# Make predictions
prediction = model.predict(features=test)

# Evaluate the model
metrics = model.get_metrics()
print(metrics)
```

This example demonstrates how to use Fedot to automate the machine learning pipeline design for a classification problem. For more detailed options and parameters, you can refer to the Fedot documentation.

**Comment by valer1435** [comment]
What if my data is already loaded in memory as pandas Dataframe?

**Comment by valer1435** [comment]
What if my data is already loaded in memory as pandas Dataframe? @RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
@valer1435 If your data is already loaded in memory as a pandas DataFrame, you can directly use it with the Fedot API without needing to read from a CSV file. Here's how you can proceed:

1. **Ensure your data is in a pandas DataFrame**:
   ```python
   import pandas as pd
   train_df = pd.DataFrame(...)  # Your training data
   test_df = pd.DataFrame(...)    # Your test data
   ```

2. **Initialize the Fedot object for classification**:
   ```python
   from fedot.api.main import Fedot
   model = Fedot(problem='classification', metric='roc_auc')
   ```

3. **Fit the model to your training data**:
   ```python
   best_pipeline = model.fit(features=train_df, target='target')
   ```

4. **Make predictions on the test data**:
   ```python
   prediction = model.predict(features=test_df)
   ```

5. **Evaluate the model's performance**:
   ```python
   metrics = model.get_metrics()
   print(metrics)
   ```

Here's a complete example:

```python
from fedot.api.main import Fedot
import pandas as pd

# Assume train_df and test_df are already loaded pandas DataFrames
train_df = pd.DataFrame(...)  # Your training data
test_df = pd.DataFrame(...)   # Your test data

# Initialize Fedot for classification
model = Fedot(problem='classification', metric='roc_auc')

# Fit the model
best_pipeline = model.fit(features=train_df, target='target')

# Make predictions
prediction = model.predict(features=test_df)

# Evaluate the model
metrics = model.get_metrics()
print(metrics)
```

This example shows how to use Fedot with data already in memory as pandas DataFrames. For more detailed options and parameters, you can refer to the Fedot documentation.
