### ISSUE TITLE
Test 2

### ISSUE THREAD

**Issue by valer1435** [valer1435/RepoPilot#8]
How to solve table classification task with fedot?

**Comment by valer1435** [comment]
@RepoPilotAssistant

**Comment by RepoPilotAssistant** [comment]
Sorry, I've not understood your question. Please tag me like  RepoPilotAssistant help <Your question>

**Comment by valer1435** [comment]
@RepoPilotAssistant help

**Comment by RepoPilotAssistant** [comment]
Sorry, I've not understood your question. Please tag me like  RepoPilotAssistant help <Your question>
